config/routes.rb
Rails.application.routes.draw do
  
  root to :'movies#index'
  resources :customers



  get 'm_t/t1'

  get 'm_t/t2'

  get 'reviews/index'

  get 'reviews/show'

  get 'reviews/new'

  get 'reviews/edit'

  


  resources :movies do
  	resources:reviews

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many:reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:fname, :lname)
    end
end

app/controllers/m_t_controller.rb
class MTController < ApplicationController
  def t1
  end

  def t2
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :release)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /movies/1/reviews
def index
# For URL like /movies/1/reviews
# Get the movie with id=1
  @movie = Movie.find(params[:movie_id])
# Access all reviews for that movie
  @reviews = @movie.reviews
end
# GET /movies/1/reviews/2
def show
  @movie = Movie.find(params[:movie_id])
# For URL like /movies/1/reviews/2
# Find an review in movies 1 that has id=2
  @review = @movie.reviews.find(params[:id])
end
# GET /movies/1/reviews/new
def new
  @movie = Movie.find(params[:movie_id])
# Associate an review object with movie 1
  @review = @movie.reviews.build
end
# POST /movies/1/reviews
def create
  @movie = Movie.find(params[:movie_id])

# For URL like /movies/1/reviews
# Populate an review associate with movie 1 with form data
# Movie will be associated with the review
# @review = @movie.reviews.build(params.require(:review).permit!)
  @review = @movie.reviews.build(params.require(:review).permit(:details))
  if @review.save
# Save the review successfully
     redirect_to movie_review_url(@movie, @review)
  else
     render :action => "new"
  end
end
# GET /movies/1/reviews/2/edit
def edit
  @movie = Movie.find(params[:movie_id])
# For URL like /movies/1/reviews/2/edit
# Get review id=2 for movie 1
  @review = @movie.reviews.find(params[:id])
end
# PUT /movies/1/reviews/2
def update
  @movie = Movie.find(params[:movie_id])
  @review = Review.find(params[:id])
  if @review.update_attributes(params.require(:review).permit(:details))
# Save the review successfully
     redirect_to movie_review_url(@movie, @review)
  else
     render :action => "edit"
  end
end
# DELETE /movies/1/reviews/2
def destroy
  @movie = Movie.find(params[:movie_id])

  @review = Review.find(params[:id])
  @review.destroy
  respond_to do |format|
    format.html { redirect_to movie_reviews_path(@movie) }
    format.xml { head :ok }
  end
 end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/m_t_helper.rb
module MTHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %>
    <%= f.text_field :fname %>
  </div>

  <div class="field">
    <%= f.label :lname %>
    <%= f.text_field :lname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.fname %></td>
        <td><%= customer.lname %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @customer.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @customer.lname %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/m_t/t1.html.erb
<h1>MT#t1</h1>
<p>Find me in app/views/m_t/t1.html.erb</p>

app/views/m_t/t2.html.erb
<h1>MT#t2</h1>
<p>Find me in app/views/m_t/t2.html.erb</p>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>

  <div class="field">
    <%= f.label :release %>
    <%= f.text_field :release %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Release</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.release %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<strong>Title:</strong>
<%= @movie.title %>
</p>
<p>
<strong>Rating:</strong>
<%= @movie.rating %>
</p>
<p>
<strong>Release Date:</strong>
<%= @movie.release %>
</p>
<!-- Display the reviews of a movie -->
<h2>Reviews</h2>
<% @movie.reviews.each do |review| %>
<p>
<b>Review details:</b>
<%= review.details %>
</p>
<% end %>
<%= link_to 'Edit Movie', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %> |
<%= link_to 'Show Reviews', movie_reviews_path(@movie) %>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
<% if @review.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@review.errors.count, "error")%>
prohibited this review from being saved:</h2>
<ul>
<% @review.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<p>
<%= f.label :Details %><br />
<%= f.text_field :details %>
</p>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>
<%= render 'form' %>
<%= link_to 'Show', movie_review_path(@movie, @review) %> |
<%= link_to 'Back', movie_reviews_path(@movie) %>

app/views/reviews/index.html.erb
<h1>Reviews in <%= @movie.title %></h1>
<table>
<tr>
<th>Review details</th>
</tr>
<% for review in @reviews %>
<tr>
<td><%= review.details %></td>
<td><%= link_to 'Show', movie_review_path(@movie, review)
%></td>
<td><%= link_to 'Edit', edit_movie_review_path(@movie, review)
%></td>
<td><%= link_to 'Destroy', movie_review_path(@movie, review),
:confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
</table>
<br />
<%= link_to 'New review', new_movie_review_path(@movie) %>
<%= link_to 'Back to Movie', @movie %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= render 'form' %>
<%= link_to 'Back', movie_reviews_path(@movie) %>

app/views/reviews/show.html.erb
<h1>Review in <%= @movie.title %></h1>
<p>
<b>Review details:</b>
<%= @review.details %>
</p>
<%= link_to 'Edit', edit_movie_review_path(@movie, @review) %> |
<%= link_to 'Back', movie_reviews_path(@movie) %>